version: '3'

services:
  test_cases:
    image: bike-rental
    command: python manage.py test
    volumes:
      - .:/app
  web:
    image: bike-rental
    command: gunicorn BikeRental.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - /static:/static
    ports:
      - "8000:8000"
    restart: always

  nginx:
    build: ./nginx
    volumes:
      - /static:/static
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  static_volume:
